version: '3.7'
services:
  ethmonitor:
    image: darcherframework/ethereum-todolist:latest
    entrypoint: ["/bin/sh", "entry-cluster-ethmonitor.sh"]
    stop_signal: SIGINT
    stdin_open: true
    tty: true
    environment:
      ETHMONITOR_PORT: 8989
      ETHMONITOR_CONTROLLER: ${ETHMONITOR_CONTROLLER:-trivial}
      VERBOSITY: ${VERBOSITY:-4}
      ANALYZER_ADDR: ${ANALYZER_ADDR:-host.docker.internal:1234}

  doer:
    image: darcherframework/ethereum-todolist:latest
    entrypoint: ["/bin/sh", "entry-cluster-doer.sh"]
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: ${ETHASH:-~/.ethash}
        target: /.ethash
    environment:
      ETHMONITOR_ADDR: ethmonitor:8989
      VERBOSITY: 3
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "30303:30303"
      - "30303:30303/udp"

  talker:
    image: darcherframework/ethereum-todolist:latest
    entrypoint: ["/bin/sh", "entry-cluster-talker.sh"]
    stop_signal: SIGINT
    network_mode: service:doer
    volumes:
      - type: bind
        source: ${ETHASH:-~/.ethash}
        target: /.ethash
    environment:
      ETHMONITOR_ADDR: ethmonitor:8989
      VERBOSITY: 3

  dapp:
    image: darcherframework/ethereum-todolist:latest
    entrypoint: ["/bin/sh", "start-dapp.sh"]
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: ${COVERAGE_DIR:-.nyc_output}
        target: /ethereum-todolist/.nyc_output
    ports:
      - "3000:3000"
